version: '3.8'

services:
  
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=notesdb
    ports:
      - "3306:3306"
    
  
  app:
    build: .
    image: notes-app
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]  # Cambia la ruta según tu configuración
      interval: 5s
      timeout: 10s
      retries: 3
    
